spring.application.name=ecommerce-backend

server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_backend
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stripe.secret.key=sk_test_your_key_here

